/*
 * teec_error_constants.h
 *
 *  Created on: Feb 20, 2013
 *      Author: Andreas Fitzek 
 *       Email: andreas.fitzek@gmail.com
 */

#ifndef TEEC_ERROR_CONSTANTS_H_
#define TEEC_ERROR_CONSTANTS_H_

#define TEEC_SUCCESS 					TEE_SUCCESS
#define TEEC_ERROR_GENERIC 				TEE_ERROR_GENERIC
#define TEEC_ERROR_ACCESS_DENIED 		TEE_ERROR_ACCESS_DENIED
#define TEEC_ERROR_CANCEL 				TEE_ERROR_CANCEL
#define TEEC_ERROR_ACCESS_CONFLICT 		TEE_ERROR_ACCESS_CONFLICT
#define TEEC_ERROR_EXCESS_DATA 			TEE_ERROR_EXCESS_DATA
#define TEEC_ERROR_BAD_FORMAT 			TEE_ERROR_BAD_FORMAT
#define TEEC_ERROR_BAD_PARAMETERS 		TEE_ERROR_BAD_PARAMETERS
#define TEEC_ERROR_BAD_STATE 			TEE_ERROR_BAD_STATE
#define TEEC_ERROR_ITEM_NOT_FOUND 		TEE_ERROR_ITEM_NOT_FOUND
#define TEEC_ERROR_NOT_IMPLEMENTED 		TEE_ERROR_NOT_IMPLEMENTED
#define TEEC_ERROR_NOT_SUPPORTED 		TEE_ERROR_NOT_SUPPORTED
#define TEEC_ERROR_NO_DATA 				TEE_ERROR_NO_DATA
#define TEEC_ERROR_OUT_OF_MEMORY 		TEE_ERROR_OUT_OF_MEMORY
#define TEEC_ERROR_BUSY 				TEE_ERROR_BUSY
#define TEEC_ERROR_COMMUNICATION 		TEE_ERROR_COMMUNICATION
#define TEEC_ERROR_SECURITY 			TEE_ERROR_SECURITY
#define TEEC_ERROR_SHORT_BUFFER 		TEE_ERROR_SHORT_BUFFER
#define TEEC_ERROR_TARGET_DEAD 			TEE_ERROR_TARGET_DEAD

#endif /* TEEC_ERROR_CONSTANTS_H_ */
