
ARMCC := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)gcc
ARMAS := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)gcc
ARMAR := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)ar
ARMNM := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)nm
ARMOBJCOPY := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)objcopy
ARMLD := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)ld