
#ARMCC := /home/andy/bin/$(ARM_PREFIX)gcc
#ARMCC := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)clang
ARMCC := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)gcc
ARMAS := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)gcc
ARMRAS := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)as
ARMAR := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)ar
ARMNM := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)nm
ARMOBJCOPY := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)objcopy
ARMLD := $(ARM_TOOLCHAIN_DIR)$(ARM_PREFIX)ld

ARMNORMCC := $(ARM_NORM_TOOLCHAIN_DIR)$(ARM_NORM_PREFIX)gcc
ARMNORMAS := $(ARM_NORM_TOOLCHAIN_DIR)$(ARM_NORM_PREFIX)gcc
ARMNORMAR := $(ARM_NORM_TOOLCHAIN_DIR)$(ARM_NORM_PREFIX)ar
ARMNORMNM := $(ARM_NORM_TOOLCHAIN_DIR)$(ARM_NORM_PREFIX)nm
ARMNORMOBJCOPY := $(ARM_NORM_TOOLCHAIN_DIR)$(ARM_NORM_PREFIX)objcopy
ARMNORMLD := $(ARM_NORM_TOOLCHAIN_DIR)$(ARM_NORM_PREFIX)ld
