
CC := $(HOST_TOOLCHAIN_DIR)$(HOST_PREFIX)gcc
AS := $(HOST_TOOLCHAIN_DIR)$(HOST_PREFIX)gcc
AR := $(HOST_TOOLCHAIN_DIR)$(HOST_PREFIX)ar
NM := $(HOST_TOOLCHAIN_DIR)$(HOST_PREFIX)nm
OBJCOPY := $(HOST_TOOLCHAIN_DIR)$(HOST_PREFIX)objcopy
LD := $(HOST_TOOLCHAIN_DIR)$(HOST_PREFIX)ld